title: Jayshree Sarathy 
url: "https://jksarathy.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Policy & Practice"
   link: "policy"
 - name: "Teaching"
   link: "teaching"
 - name: "Bio"
   link: "bio"
 - name: "ResPECT Lab"
   link: "respect-lab"
 
